### PR TITLE
Fix namespaces

### PR DESCRIPTION
**Pull request by RalphBln**
The recent prefix fix put everything into the core namespace, including the situation-related entities. This PR puts the situation-related entities back into the situation namespace.

### CODE REVIEW

**Comment by ChristophB** [comment]
My guess is that the formatting changes are related to the different versions of the OWL API used to write the TTL file (4.5.9.2019-02-01T07:24:44Z vs. 4.5.29.2024-05-13T12:11:03Z). To simplify the review process, we should stick to one version.

**Comment by RalphBln** [comment]
The whitespace changes are a direct and expected result from the renaming operations (the ttl serializer used by the OWL API indents predicate and object lists so that predicates/objects align with their respective counterparts from the triple they refer to, so the extra whitespaces are expected indentation adjustments due to length changes of entity names).

Also, the reorderings of entities are expected, as the ttl serializer orders triples by subject IRI, and the IRIs of the situation-related entities changed in this commit.

Tested with the five-year old Protege version (5.5.0 / OWL API 4.5.9) that the original ttl file was produced with, and it doesn't make a difference.

**Comment by ChristophB** [comment]
As this is just a PR into #48, which introduces the file `gfo-situation.ttl`, it is OK to merge it - from a file-formatting-perspective.

**Comment by k00ni** [comment]
Well, I will leave it at this to not pollute this PR with more off-topic comments. If you are interested in a discussion and potential optimizations in this regard let me know I'd be happy to provide more insights.

**Review by AlexU75 — APPROVED** [review]

**Pull request merged**
